# Примеры marimo
["Оглавление"]
["Оглавление"."01"]
"name" = "Пример 01"
"title" = "Первый блокнот marimo"
"url" = "a02_01.py"
"app_type" = "marimo"
"prm" =  ""

# ...

["Оглавление"."20"]
"name" = "Пример 20"
"title" = "Работаем с toml"
"url" = "a02_20.py"
"app_type" = "marimo"
"prm" =  ""


["Оглавление"."21"]
"name" = "Пример 21"
"title" = "3d в блокноте marimo"
"url" = "a02_21.py"
"app_type" = "marimo"
"prm" =  ""
